Don't try and set noschg on missing directories
My setup:

% pkg info -x poudriere
poudriere-devel-3.4.99.20251026

% uname -a
FreeBSD pkg.infracaninophile.co.uk 14.3-STABLE FreeBSD 14.3-STABLE stable/14-c10884484342 GENERIC amd64

% poudriere jails -l | grep stable14
stable14amd64 14.1-STABLE                              amd64 pkgbase   2025-10-25 10:53:58 /usr/local/poudriere/jails/stable14amd64
stable14base  14.3-STABLE 1403506 c108844843           amd64 git+https 2025-10-23 13:01:10 /usr/local/poudriere/jails/stable14base

where I build base packages in the `stable14base` jail, and these are
used both on my host systems and in the make package building jail.

poudriere-devel fails like so:

```
[00:00:00] Creating the reference jail... done
[00:00:02] Mounting system devices for stable14amd64-default
[00:00:02] Stashing existing package repository
[00:00:02] Mounting ccache from: /var/cache/ccache
[00:00:02] Mounting ports from: /usr/ports
[00:00:02] Mounting packages from: /usr/local/poudriere/data/packages/stable14amd64-default
[00:00:02] Mounting distfiles from: /usr/ports/distfiles
[00:00:02] Copying /var/db/ports from: /usr/local/etc/poudriere.d/options
[00:00:02] Appending to make.conf: /usr/local/etc/poudriere.d/make.conf
/etc/resolv.conf -> /usr/local/poudriere/data/.m/stable14amd64-default/ref/etc/resolv.conf
[00:00:02] Starting jail stable14amd64-default
Updating /var/run/os-release done.
[00:00:03] Will build as nobody:nobody (65534:65534)
[00:00:04] Setting schg on jail base paths
chflags: /usr/local/poudriere/data/.m/stable14amd64-default/ref/boot/modules: No such file or directory
chflags: /usr/local/poudriere/data/.m/stable14amd64-default/ref/boot/firmware: No such file or directory
Error: (24040) /usr/local/share/poudriere/bulk.sh:/usr/local/share/poudriere/bulk.sh:255:jail_start:255: set -e error: status = 1
[ERROR] Unhandled error!
[00:00:04] Cleaning up
[00:00:04] Unmounting file systems
Exiting with status 1
```

The /boot/modules amd /boot/firmware directories are missing from my
package building jail, which make it difficult to `chflags -R noschg`
those directories.