eargs: Support showing passed in vars
Requires adding to the end of the eargs line:
	EARGS: "$@"
This passes in the positional parameters which allows seeing them
properly grouped.

	# ./poudriere api 'hash_get'
	Error: hash_get: 3 arguments expected, got 0:
	        Expected: hash_get var key var_return
	        Missing:  var key var_return
	# ./poudriere api 'hash_get 1'
	Error: hash_get: 3 arguments expected, got 1:
	        Expected: hash_get var key var_return
	        Received: hash_get "1"
	        Missing:  key var_return
	# ./poudriere api 'hash_get 1 2'
	Error: hash_get: 3 arguments expected, got 2:
	        Expected: hash_get var key var_return
	        Received: hash_get "1" "2"
	        Missing:  var_return
	# ./poudriere api 'hash_get 1 2 3 4 "5 6" 7'
	Error: hash_get: 3 arguments expected, got 6:
	        Expected: hash_get var key var_return
	        Received: hash_get "1" "2" "3" ??="4" ??="5 6" ??="7"